file_dir:
    md: C:\Documents and Settings\Administrator\桌面
    mm: D:\GitHub\WorkingTools\FreeMindTools
    # mddir:/home/rain/doc/samrain.github.com/_posts
default.mm:
    mdfname: default.md
    layout: post
    category: 学习
    tags: default
    title: default-title
    mmLink: http://samrainhan.github.com
差额选举的奥秘.mm:
    mdfname: 2012-11-19-What\s-the-Competitive-election.md
    layout: post
    category: manage
    tags: 选举,评优,评选
    title: 什么是差额选举？
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeINjVkb1lFajZXWVk
Markdown语法.mm:
    mdfname: 2012-11-22-Markdown-Grammar.md
    layout: post
    category: tech
    tags: 轻,github,博客,markdown,平板文件
    title: Markdown语法
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIMmhPN3Bvc0ZlZG8
Sublime Text2.mm:
    mdfname: 2012-11-22-Sublime-Text2.md
    layout: post
    category: tech
    tags: 轻,文本编辑器,ide
    title: Sublime Text2简介
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIN1ZzSTg5TmQyVzA
Github简单使用.mm:
    mdfname: 2012-11-27-Simple-to-use-Github.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,项目博客,产品博客
    title: Github简单使用
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeILXhqWG1tZmVYT28
双软认证.mm:
    mdfname: 2012-11-28-The-identification-software-companies-and-software-product-registration.md
    layout: post
    category: company
    tags: 资质认证,企业优惠,减免税,双软认证,双软认定
    title: what are 双软认证
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRGQ2NTJkQng5a1U
程序员的阅读清单.mm:
    mdfname: 2012-11-30-Programmer-reading-list.md
    layout: post
    category: tech
    tags: 程序员阅读,阅读清单,教科书,课外读物
    title: 程序员的阅读清单
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdkY2RVdSLWtLc0U
通过Github建博客.mm:
    mdfname: 2012-12-10-Built-blog-by-github.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,建博客
    title: 通过Github建博客
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRVczRmZtRV85RFk
用Freemind写博客.mm:
    mdfname: 2012-12-10-write-blog-by-freemind.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,建博客
    title: 用Freemind写博客
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdXZ1enJYbUNEV2M
实习生课程表.mm:
    mdfname: 2012-12-16-intern-curriculum.md
    layout: post
    category: manage
    tags: 实习生,课程,实习生课程
    title: 实习生课程表
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIZzduOURwampJaHM
旅游风景区清单.mm:
    mdfname: 2012-12-28-list-of-tourism-scenic-area.md
    layout: post
    category: family
    tags: 旅游,风景区,旅行
    title: 旅游风景区清单
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeISDFnbTVFZjgwSTQ
2013元旦温泉游.mm:
    mdfname: 2012-12-28-2013-new-year-day-spa-tour.md
    layout: post
    category: family
    tags: 2013元旦,温泉,黄山,歙县,旅行
    title: 2013元旦温泉游
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRlk2YTNEZ08zaWc
江浙温泉大全.mm:
    mdfname: 2012-12-28-2013-Jiangsu-and-zhejiang-spa-daquan.md
    layout: post
    category: family
    tags: 温泉,江苏,浙江,上海,旅行
    title: 江浙温泉大全
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdnVkcjdTOXQxMlU
如何把VIM变成Python IDE.mm:
    mdfname: 2012-08-16-how-to-become-VIM-python-IDE.md
    layout: post
    category: tech
    tags: VIM,python,IDE
    title: 如何把VIM变成Python IDE
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIaFMzZnJ4UWgwdEU
旅游-清迈-攻略.mm:
    mdfname: 2013-01-15-Chiang-Mai-travel-Raiders.md
    layout: post
    category: family
    tags: 旅游,清迈,攻略
    title: 清迈旅游攻略
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIUUxMWWxNVTltMHM/edit
Git命令释义.mm:
    mdfname: 2013-01-15-Git-command-Interpretation.md
    layout: post
    category: tech
    tags: Git,Git命令
    title: Git命令释义
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIRGFfRGdlYkJOU0k/edit
使用VPN-命令行CLI方式-ubuntu.mm:
    mdfname: 2013-01-15-use-VPN-by-CLI-command-on-Ubuntu.md
    layout: post
    category: tech
    tags: VPN,Ubuntu,CLI
    title: 在Ubuntu上使用命令行CLI方式使用VPN
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIbWRnWDNwT0NtcG8/edit
Install Gentoo In Virtualbox.mm:
    mdfname: 2013-01-15-Install-Gentoo-In-Virtualbox.md
    layout: post
    category: tech
    tags: Gentoo,Virtualbox,虚拟机,linux
    title: Install Gentoo In Virtualbox
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIT2t2cDlpMWI3anM/edit
解密磁盘碎片.mm:
    mdfname: 2013-01-15-Disk-fragmentation.md
    layout: post
    category: tech
    tags: fragmentation,disk,linux,磁盘碎片
    title: 解密磁盘碎片
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIN0otdUZvc2g0OTA/edit