file_dir:
    md: /home/rain/download
    mm: /home/rain/download/MM
    # md:/home/rain/doc/samrain.github.com/_posts
default.mm:
    mdfname: default.md
    layout: post
    category: 学习
    tags: default
    title: default-title
    mmLink: http://samrainhan.github.com
差额选举的奥秘.mm:
    mdfname: 2012-11-19-What\s-the-Competitive-election.md
    layout: post
    category: manage
    tags: 选举,评优,评选
    title: 什么是差额选举？
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeINjVkb1lFajZXWVk
Markdown语法.mm:
    mdfname: 2012-11-22-Markdown-Grammar.md
    layout: post
    category: tech
    tags: 轻,github,博客,markdown,平板文件
    title: Markdown语法
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIMmhPN3Bvc0ZlZG8
Sublime Text2.mm:
    mdfname: 2012-11-22-Sublime-Text2.md
    layout: post
    category: tech
    tags: 轻,文本编辑器,ide
    title: Sublime Text2简介
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIN1ZzSTg5TmQyVzA
Github简单使用.mm:
    mdfname: 2012-11-27-Simple-to-use-Github.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,项目博客,产品博客
    title: Github简单使用
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeILXhqWG1tZmVYT28
双软认证.mm:
    mdfname: 2012-11-28-The-identification-software-companies-and-software-product-registration.md
    layout: post
    category: company
    tags: 资质认证,企业优惠,减免税,双软认证,双软认定
    title: what are 双软认证
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRGQ2NTJkQng5a1U
程序员的阅读清单.mm:
    mdfname: 2012-11-30-Programmer-reading-list.md
    layout: post
    category: tech
    tags: 程序员阅读,阅读清单,教科书,课外读物
    title: 程序员的阅读清单
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdkY2RVdSLWtLc0U
通过Github建博客.mm:
    mdfname: 2012-12-10-Built-blog-by-github.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,建博客
    title: 通过Github建博客
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRVczRmZtRV85RFk
用Freemind写博客.mm:
    mdfname: 2012-12-10-write-blog-by-freemind.md
    layout: post
    category: tech
    tags: git,版本控制系统,在线代码托管,个人博客,建博客
    title: 用Freemind写博客
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdXZ1enJYbUNEV2M
实习生课程表.mm:
    mdfname: 2012-12-16-intern-curriculum.md
    layout: post
    category: manage
    tags: 实习生,课程,实习生课程
    title: 实习生课程表
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIZzduOURwampJaHM
旅游风景区清单.mm:
    mdfname: 2012-12-28-list-of-tourism-scenic-area.md
    layout: post
    category: family
    tags: 旅游,风景区,旅行
    title: 旅游风景区清单
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeISDFnbTVFZjgwSTQ
2013元旦温泉游.mm:
    mdfname: 2012-12-28-2013-new-year-day-spa-tour.md
    layout: post
    category: family
    tags: 2013元旦,温泉,黄山,歙县,旅行
    title: 2013元旦温泉游
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIRlk2YTNEZ08zaWc
江浙温泉大全.mm:
    mdfname: 2012-12-28-2013-Jiangsu-and-zhejiang-spa-daquan.md
    layout: post
    category: family
    tags: 温泉,江苏,浙江,上海,旅行
    title: 江浙温泉大全
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIdnVkcjdTOXQxMlU
如何把VIM变成Python IDE.mm:
    mdfname: 2012-08-16-how-to-become-VIM-python-IDE.md
    layout: post
    category: tech
    tags: VIM,python,IDE
    title: 如何把VIM变成Python IDE
    mmLink: https://docs.google.com/open?id=0B1DrsqrLRzeIaFMzZnJ4UWgwdEU
旅游-清迈-攻略.mm:
    mdfname: 2013-01-15-Chiang-Mai-travel-Raiders.md
    layout: post
    category: family
    tags: 旅游,清迈,攻略
    title: 清迈旅游攻略
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIUUxMWWxNVTltMHM/edit
Git命令释义.mm:
    mdfname: 2013-01-15-Git-command-Interpretation.md
    layout: post
    category: tech
    tags: Git,Git命令
    title: Git命令释义
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIRGFfRGdlYkJOU0k/edit
使用VPN-命令行CLI方式-ubuntu.mm:
    mdfname: 2013-01-15-use-VPN-by-CLI-command-on-Ubuntu.md
    layout: post
    category: tech
    tags: VPN,Ubuntu,CLI
    title: 在Ubuntu上使用命令行CLI方式使用VPN
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIbWRnWDNwT0NtcG8/edit
Install Gentoo In Virtualbox.mm:
    mdfname: 2013-01-15-Install-Gentoo-In-Virtualbox.md
    layout: post
    category: tech
    tags: Gentoo,Virtualbox,虚拟机,linux
    title: Install Gentoo In Virtualbox
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIT2t2cDlpMWI3anM/edit
解密磁盘碎片.mm:
    mdfname: 2013-01-15-Disk-fragmentation.md
    layout: post
    category: tech
    tags: fragmentation,disk,linux,磁盘碎片
    title: 解密磁盘碎片
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIN0otdUZvc2g0OTA/edit
Chrome介绍.mm:
    mdfname: 2013-03-11-Chrome.md
    layout: post
    category: tech
    tags: chrome,browser,google,chromium
    title: Chrome介绍
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIWk1TNXZOdkpMUGs/edit
GOOGLE搜索从入门到精通.mm:
    mdfname: 2013-03-11-google-search-tips.md
    layout: post
    category: tech
    tags: google,search,tips
    title: GOOGLE搜索从入门到精通
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIdFIzcENLWDJVTG8/edit?usp=sharing
小儿常用药.mm:
    mdfname: 2013-03-11-commonly-used-drugs-in-children.md
    layout: post
    category: family
    tags: drugs,children,medicine,sickness,fault
    title: 小儿常用药
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIUFVsY09QalI2aU0/edit?usp=sharing
VI学习.mm:
    mdfname: 2013-03-11-study-VI.md
    layout: post
    category: tech
    tags: VI,VIM
    title: 学习VI
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIODc4ZDhJQmI4Ym8/edit?usp=sharing
PPT模板和素材.mm:
    mdfname: 2013-03-18-PPT-templates-and-clip.md
    layout: post
    category: study
    tags: PPT,template,clip,presentation
    title: PPT模板和素材
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeINVgyeFpjN2N4ODA/edit?usp=sharing
Gmail快捷键.mm:
    mdfname: 2013-03-18-Gmail-shortcuts.md
    layout: post
    category: tech
    tags: Gmail,shortcuts,google
    title: Gmail快捷键
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeINWk1ZzZYWXZ2dE0/edit?usp=sharing
个人知识管理平台.mm:
    mdfname: 2013-03-21-personal-knowledge-management-platform.md
    layout: post
    category: study
    tags: knowledge,manage,personal
    title: 个人知识管理平台
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIaDl3YW1BYnhPMjA/edit?usp=sharing
我的工具.mm:
    mdfname: 2013-03-21-my-tools.md
    layout: post
    category: tech
    tags: 工具,tool
    title: 我的工具
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIbkJ1NmwycE90WUk/edit?usp=sharing
ITIL.mm:
    mdfname: 2013-03-25-learn-ITIL.md
    layout: post
    category: tech
    tags: ITIL,learn
    title: ITIL
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIeXZOQkp0OXBjMzA/edit?usp=sharing
LearnPython.mm:
    mdfname: 2013-03-25-learn-python.md
    layout: post
    category: tech
    tags: python
    title: LearnPython
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIcXFBNUpOdm5zaU0/edit?usp=sharing
MeetingMinutes.mm:
    mdfname: 2013-03-25-template-of-meeting-minutes.md
    layout: post
    category: tech
    tags: meeting minutes,template
    title: 会议纪要模版
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIc004MC1iWUFHRDA/edit?usp=sharing
OPENERP.mm:
    mdfname: 2013-03-25-learn-OPENERP.md
    layout: post
    category: tech
    tags: OPENERP,ERP,python
    title: OPENERP Step by Step
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIU2czNzAwQXp0YVk/edit?usp=sharing
Redmine.mm:
    mdfname: 2013-03-25-learn-redmine.md
    layout: post
    category: tech
    tags: Redmine,issue management system,bug management system
    title: learn Redmine
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQWd5X0wwVGxKSlk/edit?usp=sharing
Ubuntu@Termintor.mm:
    mdfname: 2013-03-25-How-to-set-the-Terminator-copy-and-paste-shortcuts.md
    layout: post
    category: tech
    tags: ubuntu,Termintor,shortcuts,copy,paste
    title: 怎么设置Terminator中的复制和粘帖快捷键
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIenhmbGo4aHVCbDg/edit?usp=sharing
家庭教育.mm:
    mdfname: 2013-03-25-discuss-of-family-education.md
    layout: post
    category: tech
    tags: 家庭,家庭教育,教育
    title: 讨论家庭教育
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIaWFreGxEOHEtZUE/edit?usp=sharing
企业文化摘录.mm:
    mdfname: 2013-03-25-excerpts-of-corporate-culture.md
    layout: post
    category: tech
    tags: 企业文化,文化,企业
    title: 企业文化摘录
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIcmVGcU5ScjEtbkk/edit?usp=sharing
购买全幅相机建议.mm:
    mdfname: 2013-03-25-purchase-full-size-camera-proposals.md
    layout: post
    category: tech
    tags: 购买,全幅相机,相机
    title: 购买全幅相机建议
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIQkJRSm5IM2h3c3c/edit?usp=sharing
组织技术社区会议-泉盛.mm:
    mdfname: 2013-03-25-how-to-organize-the-technical-community-meeting.md
    layout: post
    category: manage
    tags: 组织,技术社区,社区会议,技术社区会议,组织会议
    title: 如何组织技术社区会议
    mmLink: https://docs.google.com/file/d/0B1DrsqrLRzeIWW55M1VvYkxyams/edit?usp=sharing